media:
  input: src/assets/blog
  output: /assets/blog

content:
  - name: blog
    label: Blog Posts
    type: collection
    path: src/content/blog
    format: yaml-frontmatter
    fields:
      - name: title
        label: Title
        type: string
      - name: slug
        label: Slug
        type: string
      - name: author
        label: Author
        type: string
      - name: pubDate
        label: Publication Date
        type: date
      - name: image
        label: Featured Image
        type: string
      - name: tags
        label: Tags
        type: select
        list: true
      - name: description
        label: Description
        type: text
      - name: metaTitle
        label: Meta Title (SEO)
        type: string
      - name: metaDescription
        label: Meta Description (SEO)
        type: text
      - name: body
        label: Body
        type: rich-text
        options:
          image:
            storage: src/assets/blog
            public: /assets/blog
